version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: ./conf.py  # 显式指定配置文件路径

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
