version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # 根据项目需求选择 Python 版本

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs  # 如果使用 requirements/docs.txt
  system_packages: false
